[package]
name = "moka-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "moka"
crate_type = ["cdylib"]

[dependencies]
jni = "0.20.0"
moka = "0.9.6"
# moka = { git = "https://github.com/moka-rs/moka", branch = "master" }
once_cell = "1.9.0"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
